I got this error that makes me cant see shaders:
QOpenGLShader::compile(Fragment): 0(6) : error C7533: global variable
gl_FragColor is deprecated after version 120

*** Problematic Fragment shader source code ***

uniform vec3 color;

void main(void) {
    gl_FragColor = vec4(color, 1.0);
}

***

This relates to my NVDI GPU and I should changed the version to 120.